### DISCUSSION TITLE
Mongodb replicaset with x.509 Certificate auth

### DISCUSSION THREAD

**Discussion by D3an1el** [moghtech/komodo#192] [Q&A]
Hi, i have mongodb in a replicaset and trying to use the db uri but get 

```
Caused by:
    0: failed to init mongo with given args
    1: Kind: I/O error: No such file or directory (os error 2), labels: {}
```
Below is the command string i use for `database.uri`
```
database.uri = "mongodb+srv://mongocluster.example.com/komodo?replicaSet=rs0&tlsCertificateKeyFile=mongodb-komodo-client.pem&tlsCAFile=ca-chain-bundle.cert.pem"
```

is it possible for this to work?

**Comment by mbecker20** [comment]
The URI is parsed using the official mongo client using this method: https://docs.rs/mongodb/latest/mongodb/options/struct.ClientOptions.html#method.parse. It should support this URI.

It says it can't find a file, and you are passing the cert files in the URI. Are these mounted into the container? To be explicit, the paths to files in URI should be absolute path.

**Comment by D3an1el** [comment]
yeah, but still fails. Looks like the query adds the domain twice.

https://paste.sethforprivacy.com/?9a12ecf8f94f9501#4BvUrdTS4e3wr4ULSUXQ8Csahf7tbZXU79LyUDrGpUX5

uri works with mongosh also.

**Comment by mbecker20** [comment]
It seems the issue is still "file not found", see the third to last line of your debug log, it must be that it cannot find the cert files at the path you give it. I can't think of any other reason initializing mongo client would fail with "file not found" error.

**Comment by mbecker20** [comment]
Can you send the current config you use for this part: 
```
tlsCertificateKeyFile=/certs/mongodb-komodo-client.pem&tlsCAFile=/certs/ca-chain-bundle.cert.pem
```

And how you mount the certs into contianer, should have something like:

```
  volumes:
    - /path/to/certs:/certs
    - ...
```

**Reply by D3an1el** [reply]
> Can you send the current config you use for this part:
> 
> ```
> tlsCertificateKeyFile=/certs/mongodb-komodo-client.pem&tlsCAFile=/certs/ca-chain-bundle.cert.pem
> ```
> 
> And how you mount the certs into contianer, should have something like:
> 
> ```
>   volumes:
>     - /path/to/certs:/certs
>     - ...
> ```


URI String:

```
database.uri = "mongodb+srv://mongocluster.example.com/komodo?replicaSet=rs0&tlsCertificateKeyFile=/config/ssl/mongodb-komodo-client.pem&tlsCAFile=/config/ssl/ca-chain-bundle.cert.pem"
```

Compose file:
```
services:
  komodo-core:
    image: ghcr.io/mbecker20/komodo:1.16.11
    container_name: komodo
    restart: unless-stopped
    dns:
      - "192.168.1.253"
      - "192.168.1.254"
    logging:
      driver: local # enable log rotation by default. see `https://docs.docker.com/config/containers/logging/local/`
    ports:
      - 9120:9120
    extra_hosts: # allows for local periphery connection at "http://host.docker.internal:8120"
      - host.docker.internal:host-gateway
    volumes:
      - /root/komodo/komodo/core.config.toml:/config/config.toml
      - /root/komodo/komodo/:/config
  komodo-periphery:
    image: ghcr.io/mbecker20/periphery:1.16.11 # use ghcr.io/mbecker20/periphery:latest-aarch64 for arm support
    container_name: komodo-periphery
    logging:
      driver: local
    restart: unless-stopped
    ports:
      - 8120:8120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/komodo/komodo-repos:/etc/komodo/repos # manage repos in a docker volume, or change it to an accessible host directory.
      - /root/komodo/komodo-stacks:/etc/komodo/stacks # manage stack files in a docker volume, or change it to an accessible host directory.
    # environment:
    #   # If the disk size is overreporting, can use one of these to 
    #   # whitelist / blacklist the disks to filter them, whichever is easier. 
    #   PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/monitor/repos 
    #   PERIPHERY_EXCLUDE_DISK_MOUNTS: /snap

```



Docker logs:

```

komodo            |  DEBUG rustls::client::hs: Using ciphersuite TLS13_AES_256_GCM_SHA384    
komodo            |  DEBUG rustls::client::tls13: Not resuming    
komodo            |  DEBUG rustls::client::tls13: TLS1.3 encrypted extensions: [ServerNameAck]    
komodo            |  DEBUG rustls::client::hs: ALPN protocol is None    
komodo            |  DEBUG rustls::client::tls13: Got CertificateRequest CertificateRequestPayloadTLS13 { context: , extensions: [SignatureAlgorithms([ECDSA_NISTP256_SHA256, ECDSA_NISTP384_SHA384, ECDSA_NISTP521_SHA512, ED25519, ED448, Unknown(2057), Unknown(2058), Unknown(2059), RSA_PSS_SHA256, RSA_PSS_SHA384, RSA_PSS_SHA512, RSA_PKCS1_SHA256, RSA_PKCS1_SHA384, RSA_PKCS1_SHA512, Unknown(771), Unknown(769)]), AuthorityNames([DistinguishedName(3058310b30090603550406130241553113301106035504080c0a536f6d652d537461746531133011060355040a0c0a534543524554204f5247311f301d06035504030c166b657967656e2d696e7465726d656469617465204341), DistinguishedName(3059310b30090603550406130241553113301106035504080c0a536f6d652d5374617465310f300d06035504070c0653454352455431133011060355040a0c0a534543524554204f5247310f300d06035504030c066b657967656e)])] }    
komodo            |  rustls::client::common: Attempting client auth    
komodo            |  rustls::client::hs: Using ciphersuite TLS13_AES_256_GCM_SHA384    
komodo            |  rustls::client::tls13: Not resuming    
komodo            |  rustls::client::tls13: TLS1.3 encrypted extensions: [ServerNameAck]    
komodo            |  rustls::client::hs: ALPN protocol is None    
komodo            |  DEBUG rustls::client::tls13: Got CertificateRequest CertificateRequestPayloadTLS13 { context: , extensions: [SignatureAlgorithms([ECDSA_NISTP256_SHA256, ECDSA_NISTP384_SHA384, ECDSA_NISTP521_SHA512, ED25519, ED448, Unknown(2057), Unknown(2058), Unknown(2059), RSA_PSS_SHA256, RSA_PSS_SHA384, RSA_PSS_SHA512, RSA_PKCS1_SHA256, RSA_PKCS1_SHA384, RSA_PKCS1_SHA512, Unknown(771), Unknown(769)]), AuthorityNames([DistinguishedName(3058310b30090603550406130241553113301106035504080c0a536f6d652d537461746531133011060355040a0c0a534543524554204f5247311f301d06035504030c166b657967656e2d696e7465726d656469617465204341), DistinguishedName(3059310b30090603550406130241553113301106035504080c0a536f6d652d5374617465310f300d06035504070c0653454352455431133011060355040a0c0a534543524554204f5247310f300d06035504030c066b657967656e)])] }    
komodo            |  DEBUG rustls::client::common: Attempting client auth    
komodo            |  DEBUG rustls::client::hs: Using ciphersuite TLS13_AES_256_GCM_SHA384    
komodo            |  DEBUG rustls::client::tls13: Not resuming    
komodo            |  DEBUG rustls::client::tls13: TLS1.3 encrypted extensions: [ServerNameAck]    
komodo            |  DEBUG rustls::client::hs: ALPN protocol is None    
komodo            |  DEBUG rustls::client::tls13: Got CertificateRequest CertificateRequestPayloadTLS13 { context: , extensions: [SignatureAlgorithms([ECDSA_NISTP256_SHA256, ECDSA_NISTP384_SHA384, ECDSA_NISTP521_SHA512, ED25519, ED448, Unknown(2057), Unknown(2058), Unknown(2059), RSA_PSS_SHA256, RSA_PSS_SHA384, RSA_PSS_SHA512, RSA_PKCS1_SHA256, RSA_PKCS1_SHA384, RSA_PKCS1_SHA512, Unknown(771), Unknown(769)]), AuthorityNames([DistinguishedName(3058310b30090603550406130241553113301106035504080c0a536f6d652d537461746531133011060355040a0c0a534543524554204f5247311f301d06035504030c166b657967656e2d696e7465726d656469617465204341), DistinguishedName(3059310b30090603550406130241553113301106035504080c0a536f6d652d5374617465310f300d06035504070c0653454352455431133011060355040a0c0a534543524554204f5247310f300d06035504030c066b657967656e)])] }    
komodo            |  DEBUG rustls::client::common: Attempting client auth    
komodo            |  rustls::client::hs: Resuming session    
komodo            |  rustls::client::hs: Using ciphersuite TLS13_AES_256_GCM_SHA384    
komodo            |  rustls::client::tls13: Resuming using PSK    
komodo            |  DEBUG rustls::client::tls13: TLS1.3 encrypted extensions: [ServerNameAck]    
komodo            |  DEBUG rustls::client::hs: ALPN protocol is None    
komodo            | thread 'tokio-runtime-worker' panicked at bin/core/src/state.rs:46:6:
komodo            | called `Result::unwrap()` on an `Err` value: failed to initialize database client
komodo            | 
komodo            | Caused by:
komodo            |     failed to create index | index: enabled | error: Error { kind: Command(CommandError { code: 13, code_name: "Unauthorized", message: "Command createIndexes requires authentication", topology_version: None }), labels: {}, wire_version: Some(21), source: None }
komodo            | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
komodo            | Error: task 3 panicked

```

Mongodb user permissions:

```
        { role: 'readWrite', db: 'komodo' },
        { role: 'dbAdmin', db: 'komodo' }
```

I can see it getting accepted in mongodb logs, but then disconnects.
