### DISCUSSION TITLE
How do I configure a stack which is running on multiple servers?

### DISCUSSION THREAD

**Discussion by nathan815** [moghtech/komodo#232] [Q&A]
First, great project, really liking what I'm seeing in Komodo!

I have a particular stack with some prometheus exporters which I deploy on all my docker servers. I currently use Dockge which supports this since it's purely driven from the stacks folder (i.e., it doesn't have its own internal state and concept of stacks like Komodo does). 

How can I do this in Komodo?

Screenshot from Dockge:

<img width="429" alt="image" src="https://github.com/user-attachments/assets/6e0ea2a5-7960-491f-9b9a-d0311c5705d7" />

Notice "container-mgmt" stack is running on the current server and a connected server ("agent" server as Dockge calls it).

**Comment by joehand** [comment]
Similar in Komodo. Run the [periphery agent on each server](https://komo.do/docs/connect-servers). Then add them both to the core.

**Comment by nathan815** [comment]
Thanks for the reply @joehand. I have the periphery agent running on both servers. Do I need to manually create the stack for each server with a different name? Such as "container-mgmt_server1" and "container-mgmt_server2". Or is there a way to define a stack once and tell Komodo it's deployed on both servers?

**Reply by joehand** [reply]
As long as they have different names you can deploy same stack to multiple servers. For example I have my a caddy docker-compose stack deployed on a few servers. The stack is managed in git, so easy to duplicate. I imagine it doesn't work nicely with the UI or Files on Server stacks.

```toml
[[stack]]
name = "caddy-1"
[stack.config]
server = "serv-1"
run_directory = "stacks/common/caddy"
git_account = "joehand"
repo = "joehand/my-repo"
environment = """
SHARED_ENV_STUFF = [[SHARED_ENV_STUFF]]  # secret set in core.config.yml
"""

##

[[stack]]
name = "caddy-2"
[stack.config]
server = "serv-2"
run_directory = "stacks/common/caddy"
git_account = "joehand"
repo = "joehand/my-repo"
environment = """
SHARED_ENV_STUFF = [[SHARED_ENV_STUFF]] 
"""
```
