### DISCUSSION TITLE
How can I use the variables I set in UI

### DISCUSSION THREAD

**Discussion by rubenssoto** [moghtech/komodo#276] [Q&A]
Hey Guys, Komodo is amazing but I'm suffering to understand how env variables work.

I created two variables using the UI, for user and password, set both as secrets. But it is not working, docker is not receiving any value.

My docker compose

```
services:
    couchdb-obsidian-livesync:
        image: couchdb:3.3.3
        environment:
          - PUID=99
          - PGID=100
          - UMASK=0022
          - TZ=America/Sao_Paulo
          - COUCHDB_USER=${COUCHDB_USER}
          - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
        networks:
          - container-network
        volumes:
          - /data/apps/couchdb/data:/opt/couchdb/data  # Persist data
        ports:
          - 5984
        restart: unless-stopped
volumes:
  couchdb_data:
networks:
  container-network:
    external: true
``` 

![image](https://github.com/user-attachments/assets/2374e1a3-c641-4d6a-807b-ab7b34386470)

![image](https://github.com/user-attachments/assets/72f3250e-a969-4fc5-9b09-e2cb850dcfa4)
