### DISCUSSION TITLE
How do you handle a Git provider in Git Repo mode?

### DISCUSSION THREAD

**Discussion by Laflamme** [moghtech/komodo#523] [Q&A]
I currently have a Forgejo stack in File on server mode. All my other stacks use Git Repo mode with that Forgejo instance as their Git provider.

My Forgejo instance cannot act as a Git provider for itself, right? My understanding is that if Forgejo is not already deployed, Komodo won't be able to pull from it in order to deploy it. 

How would you handle this situation?

**Comment by wieluk** [comment]
Is this possible? I have the same problem.

**Reply by sweisgerber** [reply]
This is a classic boot-strapping problem (https://www.artandpopularculture.com/Baron_M%C3%BCnchhausen_pulls_himself_out_of_a_mire_by_his_own_hair).
My solution was to always push my compose files to a second location as well (codeberg), which is always available as a fallback for me.
I got a second boot-strapping problem for the periphery agents, which I simply manage via ssh & local compose files.

**Reply by Blacks-Army** [reply]
See my comment below.

**Comment by Blacks-Army** [comment]
It can.

My workflow:
1.	Renovate creates a PR.
2.	I merge the PR and accept it.
3.	Forgejo sends a webhook to Komodo’s deploy endpoint for the stack.
4.	Komodo reclones the repository first (the reclone option must be checked; for me, it reclones before destroying the stack).
5.	Komodo then destroys the stack and redeploys it with the new configuration.

Here’s the config I use:
```toml
[[stack]]
name = "forgejo_server-01"
[stack.config]
server = "server-01"
destroy_before_deploy = true
linked_repo = "forgejo_server-01"
reclone = true
webhook_force_deploy = true

[[repo]]
name = "forgejo_server-01"
[repo.config]
server = "server-01"
builder = "server-01"
git_provider = "forgejo.example.com"
git_account = "svc-komodo"
repo = "docker-compose/forgejo_server-01"
webhook_enabled = false
```
