### DISCUSSION TITLE
Periphery in Unraid (compose)

### DISCUSSION THREAD

**Discussion by Solear** [moghtech/komodo#530] [Q&A]
Hello! I'm a very happy komodo-user, I'm running komodo core on a proxmox lxc with round about 10 periphery-agents (in lxcs). It's easy: spin up the lxc, install the systemd-periphery-agent - done. 

Now I would like to install an periphery-agent on my unraid machine. 
I set up docker, installed the community plugin for docker compose.
My compose:

```
####################################
# 🦎 KOMODO COMPOSE - PERIPHERY 🦎 #
####################################

## This compose file will deploy:
##   1. Komodo Periphery

services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:latest
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: always
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    ## https://komo.do/docs/connect-servers#configuration
    environment:
      PERIPHERY_ROOT_DIRECTORY: /mnt/user/appdata/komodo
      ## Pass the same passkey as used by the Komodo Core connecting to this Periphery agent.
      PERIPHERY_PASSKEYS: abc123  
      ## Make server run over https
      PERIPHERY_SSL_ENABLED: false
      ## Specify whether to disable the terminals feature
      ## and disallow remote shell access (inside the Periphery container).
      PERIPHERY_DISABLE_TERMINALS: false
      ## If the disk size is overreporting, can use one of these to 
      ## whitelist / blacklist the disks to filter them, whichever is easier.
      ## Accepts comma separated list of paths.
      ## Usually whitelisting just /etc/hostname gives correct size for single root disk.
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
      # PERIPHERY_EXCLUDE_DISK_MOUNTS: /snap,/etc/repos
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - /mnt/user/appdata/komodo:/mnt/user/appdata/komodo
    ## If periphery is being run remote from the core server, ports need
    ## to be exposed on the host.
     ports:
       - 8120:8120
    ## If you want to use a custom periphery config file, use command to pass it to periphery.
    # command: periphery --config-path ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/periphery.config.toml
```

When I spin up this compose in unraid, it's show this error:

> yaml: line 9: did not find expected key

Do I need something else? I'm out of luck.
Thank you very much!
