### DISCUSSION TITLE
Mount /proc as Read Only

### DISCUSSION THREAD

**Discussion by Linx-ESP** [moghtech/komodo#588] [General]
From the [Docs](https://komo.do/docs/setup/ferretdb):

>       ## Allow Periphery to see processes outside of container
>       - /proc:/proc

If it is to see process only, should mounting as `:ro` still work? Right now works as rw but with ro it errors with:
``` bash
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: open /proc/thread-self/attr/apparmor/exec: read-only file system: unknown
```
tried with this just to check but still no luck.
``` yaml
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
```
