### DISCUSSION TITLE
pherivery version mismatch: how to fix?

### DISCUSSION THREAD

**Discussion by mherke** [moghtech/komodo#607] [Q&A] [answered]
Hi all,

i updated komodo from 1.17.1 to 1.18.3 and now see in my server overview the message "pherivery version mismatch". How do i fix this? I could not find any information in the doc or in the release notes.

...thanks for your support

micha

**Comment by OKok-3** [comment, marked as answer]
It's a version mismatch, nothing to worry about as Komodo is backwards compatible. To fix this, simply updating the images and redeploying your periphery should suffice, e.g., running the following in the periphery directory (where the `compose.yaml` and `.env` file lives) on your periphery host:
```
docker compose down
docker compose pull
docker compose up -d
```

**Comment by mherke** [comment]
@OKok-3 
Thank you very much for your advice. Now it looks clean again.
I have about 40 servers to manage. Is there a way to update them via mass processing or even automatically via komodo? I currently run “docker compose down && docker compose pull && docker compose up -d” in all servers via SSH, which is a bit time-consuming.

**Reply by OKok-3** [reply]
Komodo does have a Procedures function that you can schedule tasks with, but that can't be used to update the peripheries themselves as Komodo core relies on the peripheries to tell each server what to do. I suggest looking into [Ansible](https://github.com/ansible/ansible), given the amount of servers you are managing. Once you set that up it will be as simple as running just one script in your laptop to automatically update and configure everything.

**Reply by mbecker20** [reply]
Ansible is the way to go with this many periphery servers to manage. I use it with only 5 hosts.

**Comment by choozm** [comment]
Hi, 

I pull komodo core and periphery image with the 'latest' tag to run as new containers. But when I add new server and enable it, I get this "Periphery version is unknown" message, the core cannot connect to the periphery and the server state is 'NOT OK'.   

When I disable the server, the message becomes **"Pherivery version mismatch. Expected 1.18.3"** and server state is 'DISABLED'.

I did not add COMPOSE_KOMODO_IMAGE_TAG in my environment variables.
```
  core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}

  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
```

Core log:
`2025-06-21T03:10:05.081318Z  INFO core: Komodo Core version: v1.18.3`

Periphery log:
`2025-06-21T02:54:14.569284Z  INFO periphery: Komodo Periphery version: v1.18.3`


What went wrong? Are the images correct?

Thank you for your support.

**Reply by choozm** [reply]
I found the issue: I set PERIPHERY_PASSKEYS as Periphery environment variables but did not set KOMODO_PASSKEY as core environment variables.

The compose should look like this:
```
  core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    environment:
      KOMODO_PASSKEY: ${KOMODO_PASSKEY}
    ...

  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    environment:
      PERIPHERY_PASSKEYS: ${KOMODO_PASSKEY}
    ...
```

Thank you.
