### ISSUE TITLE
'compose up' command using komodo variable instead of stack name, causing failure

### ISSUE THREAD

**Issue by june012006** [moghtech/komodo#296]
My 'compose up' step on this stack is apparently as follows, 
cd /mnt/NStorage/komodo/volumes/komodo/repos/dcompose/<OPENBAU_PG_UN> && docker compose -p <OPENBAU_PG_UN> -f docker-compose.yaml --env-file .env up -d

Those <> tags should be the stack name, openbau, but komodo is replacing it with my postgress username secret for the same stack.

I get the following stderr
 Container -db-1  Creating
Error response from daemon: failed to populate volume: error while mounting volume '/mnt/.ix-apps/docker/volumes/_pg_data/_data': failed to mount local volume: mount /mnt/NStorage/komodo/volumes//pg_data:/mnt/.ix-apps/docker/volumes/_pg_data/_data, flags: 0x1000: no such file or directory

For some reason, it stripped the stack name here as well, the volumes exist as openbau_pg_data.    The real data is in the openbau folder, which was also stripped.

I'm using a git sync, and git repo.

toml:
```toml
[[stack]]
name = "openbao"
tags = ["git", "Infrastructure", "GitHub"]
[stack.config]
server = "server-s00xe"
files_on_host = true
run_directory = "/mnt/NStorage/komodo/volumes/komodo/repos/dcompose/openbao/"
file_paths = ["docker-compose.yaml"]
environment = """
  # VARIABLE = value
OPENBAO_HOST=[[OPENBAO_HOST]]
POSTGRES_USER=[[OPENBAU_PG_UN]]
POSTGRES_PASSWORD=[[OPENBAU_PG_PW]]
POSTGRES_DB=[[OPENBAO_DB_NAME]]
"""
```
```yaml
volumes:
  pg_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/NStorage/komodo/volumes/openbao/pg_data'
  openbao:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/NStorage/komodo/volumes/openbao/app_data'
networks:
  openbao:
  traefik:
    external: true

services:
  db:
    image: pgautoupgrade/pgautoupgrade:17-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB:-openbao}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB:-openbao}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      openbao:
    volumes:
      - pg_data:/var/lib/postgresql/data

  openbao:
    image: openbao/openbao:2.1.0
    command: ['server', '-config=/openbao/config/bao.conf']

    cap_add:
      - IPC_LOCK
    # ports:
    #   - 8200:8200
    depends_on:
      db:
        condition: service_healthy
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DISABLE_MLOCK=true
      - VAULT_PG_CONNECTION_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-openbao}?sslmode=disable
    healthcheck:
      interval: 2s
      retries: 10
      start_period: 5s
      test: 'wget --spider  http://127.0.0.1:8200/v1/sys/seal-status || exit 1'
      timeout: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openbao.entrypoints=web"
      - "traefik.http.routers.openbao.rule=Host(`${OPENBAO_HOST}`)"
      - "traefik.http.middlewares.openbao-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.openbao.middlewares=openbao-https-redirect"
      - "traefik.http.routers.openbao-secure.entrypoints=websecure"
      - "traefik.http.routers.openbao-secure.rule=Host(`${OPENBAO_HOST}`)"
      - "traefik.http.routers.openbao-secure.tls=true"
      - "traefik.http.routers.openbao-secure.service=openbao"
      - "traefik.http.services.openbao.loadbalancer.server.port=8200"
      - "traefik.docker.network=proxy"
    volumes:
      - ./bao.conf:/openbao/config/bao.conf
      - openbao:/openbao
    networks:
      openbao:
```
