### ISSUE TITLE
Bug – networks referenced in .env not correctly assigned

### ISSUE THREAD

**Issue by mxlb-dev** [moghtech/komodo#320]
Hi.  After transitioning from plain docker compose to Komodo all my containers are now within 'komodo_network' and not in the intended ones.
I use the Komodo UI mode.

Currently services get assigned to 'stack_net', example:

**compose.yaml:**
```
services:
myservice:
  image: image:tag
          restart: unless-stopped
          container_name: myservice
          env_file: .env
          networks:
            stack_net:
```

and then stack_net gets an individual name per stack in its corresponding .env file

```
networks:
  stack_net:
    external: true
    name: ${STACK_NETWORK_NAME}
```

**.env:**
```
STACK_NETWORK_NAME=applications_network
```

Note that there is no mention of 'komodo_network' in the compose.  I assume that Komodo defaults to 'komodo_network' as it has problems handling the above logic. But it worked before and still does, when not deploying the stack via Komodo. This applies to all stacks, not just the example one.

Adding the network directly to the service like this works though in Komodo:

```
services:
myservice:
  image: image:tag
          restart: unless-stopped
          container_name: myservice
          env_file: .env
          networks:
            applications_network

networks:
  applications_network:
    external: true
```
This way the service joins correctly 'applications_network' and is not part of 'komodo_network' as intended.
