### ISSUE TITLE
Variable replacement 'ERROR: failed to interpolate secrets into environment'

### ISSUE THREAD

**Issue by crazyelectron-io** [moghtech/komodo#348]
I defined a variable in Komodo named `HOME_ASSISTANT_PG_USER` like this:
```toml
##

[[variable]]
name = "HOME_ASSISTANT_PG_USER"
description = "Username for HomeAssistant PostgresDB access"
value = "**REDACTED**"
is_secret = true
```
In the stack configuration I assign this value to an environment variable.
```toml
[[stack]]
name = "automation"
[stack.config]
server = "homeserver"
project_name = "automation"
poll_for_updates = true
run_directory = "./stacks/automation"
git_provider = "GitHub.com"
git_account = "crazyelectron-io"
repo = "crazyelectron-io/homeserver"
environment = """
HOME_ASSISTANT_PG_USER = [[HOME_ASSISTANT_PG_USER]]
HOME_ASSISTANT_PG_DB = [[HOME_ASSISTANT_PG_DB]]
HOME_ASSISTANT_PG_PASSWORD = [[HOME_ASSISTANT_PG_PASSWORD]]
HOME_ASSISTANT_DOMAIN = [[HOME_ASSISTANT_DOMAIN]]
"""
```
But when redeploying the stack I get:
```shell
ERROR: failed to interpolate secrets into environment

TRACE:
	1: did not find any value for variable HOME_ASSISTANT_PG_USER
```
