### ISSUE TITLE
Build with static Dockerfile

### ISSUE THREAD

**Issue by nicholascioli** [moghtech/komodo#371]
I am currently using resource syncs to config my komodo instance with GitOps and it would be nice to be able to bake in the Dockerfile used by a builder so that I don't have to double configure the same git repo which contains all of the configuration. Maybe something like the following would work?

```toml
[[build]]
name = "test_logger"
description = "Logs randomly at INFO, WARN, ERROR levels to test logging setups"
tags = ["test"]

[build.config]
type="static"
builder_id = "builder-01"
dockerfile = "..."
```

**Comment by nicholascioli** [comment]
I'm currently working around this by doing something like the following:

```toml
[[build]]
name = "test_logger"
description = "Logs randomly at INFO, WARN, ERROR levels to test logging setups"
tags = ["test"]

[build.config]
builder_id = "builder-01"
repo = "some_dummy/repo"
pre_build.command = """
echo 'DOCKERFILE CONTENTS' > Dockerfile
"""
```
