### ISSUE TITLE
Cannot connect to private AWS ECR registry

### ISSUE THREAD

**Issue by devvick** [moghtech/komodo#378]
I have set up account in Settings -> Providers -> Registry Accounts using IAM access key as username and secret key as token.
I also set both in the KOMODO_AWS_ACCESS_KEY_ID and KOMODO_AWS_SECRET_ACCESS_KEY, to no avail.

I'm still getting an error during build:
```
ERROR: failed to login to docker registry

TRACE:
	1: Registry ***********.dkr.ecr.eu-west-1.amazonaws.com login error
	2: Error response from daemon: login attempt to https://***********.dkr.ecr.eu-west-1.amazonaws.com/v2/ failed with status: 401 Unauthorized
	3: End of trace
```

I don't see an option to provide credentials anywhere else in config nor documentation.

**Comment by huzky-v** [comment]
Komodo uses `echo {registry_token} | docker login {domain} --username {account} --password-stdin` to login the registry.
Can you try the command in your local environment and still get login failed?

I have encountered some special character in account (access_key) which will cause the login failed. 
Is there any of the special character in your access_key/secret_key?

**Comment by devvick** [comment]
According to the official AWS docs, the tokens are valid only for 12 hours. It's a little annoying to generate and change in the providers section every day I want to build images.
I would think that since Komodo already contains code for AWS auth, it would be able to generate the token using the IAM credentials by itself.

**Comment by Butterneck** [comment]
@devvick you can install [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper) alongside periphery (on the system or on the periphery container)

**Comment by yolanv** [comment]
Fixed this by writing a new Dockerfile where I use the periphery as base image and then install the credential helper. Not the best fix, but until it is officially supported, this will do.

**Comment by mbecker20** [comment]
Yes I am familiar with AWS ECR and used to be supported, unfortunately it was too difficult to support this officially as it is different than all other providers, so support was removed in favor of the many compatible registries.

**Comment by taufiqpsumarna** [comment]
as per @yolanv solution I build simple dockerfile

A.) Configure aws-cli and docker config
1.Install [aws-cli ](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html)
2. Configure docker config.json in `/home/ubuntu/.docker/config.json` see amazon-ecr-credential-helper [docs](https://github.com/awslabs/amazon-ecr-credential-helper?tab=readme-ov-file#docker)
```json
{
	"credHelpers": {
		"public.ecr.aws": "ecr-login",
		"<aws_account_id>.dkr.ecr.<region>.amazonaws.com": "ecr-login"
	}
}
```

B.) Create dockerfile and Build komodo-periphery with amazon-ecr-credential-helper binary

```dockerfile
FROM ghcr.io/moghtech/komodo-periphery:latest
RUN apt-get update && apt-get install -y amazon-ecr-credential-helper
```

**Command:** `docker build -t komodo-periphery:local .`

C.) Modify docker-compose.yml using local image and add volume

```yaml
####################################
# 🦎 KOMODO COMPOSE - PERIPHERY 🦎 #
####################################

## This compose file will deploy:
##   1. Komodo Periphery

services:
  periphery:
    image: komodo-periphery:local
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    ## https://komo.do/docs/connect-servers#configuration
    environment:
     ..........
     ..........
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      - /home/ubuntu/.docker:/root/.docker:ro
      - /home/ubuntu/.aws:/root/.aws:ro
````

And now I'm able to pull image from my AWS ECR private registry, thanks!

**Comment by mbecker20** [comment]
@taufiqpsumarna You can do this all in docker compose file, using `build` and `dockerfile_inline`:

```yaml
services:
  periphery:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/moghtech/komodo-periphery:latest
        RUN apt-get update && apt-get install -y amazon-ecr-credential-helper
    ## https://komo.do/docs/connect-servers#configuration
    environment:
     ..........
     ..........
```
