### ISSUE TITLE
Update check doesn't work for images names with docker.io

### ISSUE THREAD

**Issue by pelluch** [moghtech/komodo#395]
Poll for updates works well for most of my stacks. I noticed one in particular, my stack for SearXNG, did not correctly show updates when there were - in fact, if I SSH'ed into the corresponding server and did

`docker image ls`

It actually did show that there was a newer version of the offending image, which means Komodo did do a pull, but it failed to register that there was a change. After trying out a few things, I noticed one in particular: The container image as defined in my `compose.yaml` did not exactly match the image name as obtained by `docker image ls`. In my `compose.yaml`, I defined the image as `docker.io/searxng/searxng:latest`. However, `docker image ls` shows the repository as `searxng/searxng`, and the image tag from `docker image inspect` is `searxng/searxng:latest`.

It seems that images that have the `docker.io` no longer have that when pulled, a behavior that doesn't happen for repositories like `ghcr.io`. I suspect this is what causes the issue. I confirmed this by changing the image in my `compose.yaml` to be `searxng/searxng:latest` instead of  `docker.io/searxng/searxng:latest`. After doing this, Komodo started successfully showing me that there were updates for it. Concretely, here was my `compose.yaml`:

```yaml
services:

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    # ports:
    #  - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
      - TZ=${TZ}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
#    networks:
#      - searxng
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    environment:
      - TZ=${TZ}
    # network_mode: bridge

  # https://github.com/qdm12/gluetun
  gluetun:
    image: ghcr.io/qdm12/gluetun:latest
    container_name: gluetun
#    networks:
#      - searxng
    cap_add:
      - NET_ADMIN
    # The sysctl disable below is recommended for simpler IPv4-only setups.
    # If you have IPv6, you can remove that line.
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES="${SERVER_COUNTRIES}"
      - WIREGUARD_ADDRESSES="${WIREGUARD_ADDRESSES}"
      - SERVER_CITIES="${SERVER_CITIES}"
      - TZ=${TZ}
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    ports:
      # For SearXNG
      - "8080:8080/tcp"

#networks:
# searxng:

volumes:
  valkey-data2:
```

When the issue was happening, `docker image ls` outputted:

```
REPOSITORY              TAG        IMAGE ID       CREATED        SIZE
searxng/searxng         latest     0b027bbad1f6   10 hours ago   188MB
searxng/searxng         <none>     aee7e168f890   40 hours ago   188MB
valkey/valkey           8-alpine   96e8168db199   4 days ago     40.2MB
ghcr.io/qdm12/gluetun   latest     98181538b28a   2 months ago   39.5MB
```

`aee7e168f890` was the old image, still in use by my container, while the latest one was pulled by the Komodo poll for updates mechanism. In this scenario, Komodo failed to detect an update was available. I suspect the issue is in the `core/src/monitor/resource.rs` `update_stack_cache` function, here:

```rust
    let image = match deployment.config.image {
      DeploymentImage::Build { build_id, version } => {
        let (build_name, build_version) = builds
          .iter()
          .find(|build| build.id == build_id)
          .map(|b| (b.name.as_ref(), b.config.version))
          .unwrap_or(("Unknown", Default::default()));
        let version = if version.is_none() {
          build_version.to_string()
        } else {
          version.to_string()
        };
        format!("{build_name}:{version}")
      }
      DeploymentImage::Image { image } => {
        // If image already has tag, leave it,
        // otherwise default the tag to latest
        if image.contains(':') {
          image
        } else {
          format!("{image}:latest")
        }
      }
    };
```
It obtains the image, I believe, as defined in the `compose.yaml`, while the following block:

```rust
let update_available = if let Some(ContainerListItem {
      image_id: Some(curr_image_id),
      ..
    }) = &container
    {
      images
        .iter()
        .find(|i| i.name == image)
        .map(|i| &i.id != curr_image_id)
        .unwrap_or_default()
    } else {
      false
    };
```

Seems to try to obtain an exact match with what docker is providing, which in this case, fails.
I can see a few ways to handle this: You could make a special case for docker.io images - or, instead of relying on what's specified in the `compose.yaml` file, get the container's image tag by directly checking the docker image associated with the container id, and getting the image tag information from docker this way, which periphery could provide.
