### ISSUE TITLE
ResourceSyncPendingUpdate never goes away for multiple stacks that use the same compose configuration

### ISSUE THREAD

**Issue by aksvenk** [moghtech/komodo#419]
**Komodo version:** 1.7.0

I have a resource sync to a git repo in a single flat file.
Resource sync completes successfully but the changes to similarly deployed stacks are always show as pending `ResourceSyncPendingUpdate`

Here is an example of 2 problematic stacks.

```toml
[[stack]]
name = "dozzle-agent-tuna"
[stack.config]
server = "tuna"
run_directory = "dozzle"
file_paths = ["compose.agent.yaml"]
git_provider = "git.homelab.net"
git_account = "bot"
repo = "homelab/stacks"
webhook_enabled = false
```

```toml
[[stack]]
name = "dozzle-agent-nas"
[stack.config]
server = "nas"
run_directory = "dozzle"
file_paths = ["compose.agent.yaml"]
git_provider = "git.homelab.net"
git_account = "bot"
repo = "homelab/stacks"
webhook_enabled = false
```
