### ISSUE TITLE
Allow tansient containers

### ISSUE THREAD

**Issue by mtompkins** [moghtech/komodo#426]
Thanks for your work on Komodo. I've just started to examine it an hit my first bump.

I often use [atkrad/wait4x](https://github.com/wait4x/wait4x) to manually adjust startup order for some containers that need it. In a pure docker-compose.yml this will work fine. wait4x will hold downstream containers until its check passes.

For example the following docker-compose.yml waits until Traefik has started and settled into place by waiting for it's http endpoint. Komodo marks this as unhealthy presumably because it does not expect the container to gracefully exit. Looking through the Docs I didn't see a way to make this permissible or otherwise ignored. 

Is there a label I can use to allow it to exit gracefully without throwing an error??

```
services:
  whoami:
    container_name: "whoami"
    image: "traefik/whoami:latest"
    depends_on:
      wait-for-traefik-whoami:
        condition: service_completed_successfully
    hostname: whoami
    networks:
      t3-proxy:
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncronize time of container with the host system
    environment:
      TZ: America/New_York
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Wait for Traefik
  wait-for-traefik-whoami:
    container_name: "wait-for-traefik-whoami"
    image: atkrad/wait4x
    networks:
      t3-proxy:
    command: http https://some.url.endpointi --expect-status-code 200
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  t3-proxy:
    external: true
```
