### ISSUE TITLE
Web UI crash shortly after initial install

### ISSUE THREAD

**Issue by VorpalBlade** [moghtech/komodo#427]
This shows up in the browser:

```
Unexpected Application Error!
Z is undefined

S@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:1734:67729
V@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:1734:68928
ypn/f/<@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:1734:78140
f@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:1734:77399
ypn@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:1734:78513
Ry@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:49:43308
Uy@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:49:64506
WD@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:49:75415
kve@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:49:117415
WXe@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:49:116468
xZ@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:49:116290
wve@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:49:113319
Pve@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:49:123182
eM@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:49:121947
GXe@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:49:122199
VZe/JXe/<@https://komodo.vorpal.se/assets/index-M0fJSGf6.js:49:123236

💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
```

* This happens when navigating to the the server (for the local instance) shortly after starting a new server. It works but when you go to the server stats it starts doing this for the server, and it doesn't matter what sub page on the server you look at after that.
* The host is a Raspberry Pi 5 running Debian (Raspbian) 12.
* None of the containers have anything related to this error logged. I think it is purely a frontend error perhaps?
* Tag is latest as of writing this (2025-04-20)

I used the following compose (default sqlite compose file modified to use traefik as a reverse proxy and block internet access for the containers):

```yaml
#################################
# 🦎 KOMODO COMPOSE - SQLITE 🦎 #
#################################

## This compose file will deploy:
##   1. Sqlite + FerretDB Mongo adapter (https://www.ferretdb.com)
##   2. Komodo Core
##   3. Komodo Periphery

services:
  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:1
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    # ports:
    #   - 27017:27017
    networks:
      - komodo_default
    volumes:
      - sqlite-data:/state
    environment:
      - FERRETDB_HANDLER=sqlite

  core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    labels:
      - "komodo.skip" # Prevent Komodo from stopping with StopAllContainers
      - "traefik.enable=true"
      - "traefik.http.routers.komodo.rule=Host(`komodo.mydomain.example.com`)"
      - "traefik.http.routers.komodo.entrypoints=websecure"
      - "traefik.http.routers.komodo.tls.certresolver=letsencrypt"
      - "traefik.http.services.komodo.loadbalancer.server.port=9120"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped
    depends_on:
      - ferretdb
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    #ports:
    #  - 9120:9120
    networks:
      - komodo_default
      - traefik_proxy
    env_file: ./compose.env
    environment:
      KOMODO_DATABASE_ADDRESS: ferretdb
    volumes:
      ## Core cache for repos for latest commit hash / contents
      - repo-cache:/repo-cache
      ## Store sync files on server
      # - /path/to/syncs:/syncs
      ## Optionally mount a custom core.config.toml
      # - /path/to/core.config.toml:/config/config.toml
    ## Allows for systemd Periphery connection at 
    ## "http://host.docker.internal:8120"
    # extra_hosts:
    #   - host.docker.internal:host-gateway

  ## Deploy Periphery container using this block,
  ## or deploy the Periphery binary with systemd using 
  ## https://github.com/moghtech/komodo/tree/main/scripts
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    env_file: ./compose.env
    networks:
      - komodo_default
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}

volumes:
  # Sqlite
  sqlite-data:
  # Core
  repo-cache:

networks:
  komodo_default:
    name: komodo_default
    internal: true
  traefik_proxy:
    external: true
```
