### ISSUE TITLE
Authelia OIDC fails to connect

### ISSUE THREAD

**Issue by BlueCobbleStone** [moghtech/komodo#436]
I can't find how to setup oidc with Authelia:

My current config:

```
- KOMODO_OIDC_ENABLED=true
- KOMODO_OIDC_PROVIDER=https://auth.domain
- KOMODO_OIDC_REDIRECT_HOST=https://komodo.domain
- KOMODO_OIDC_CLIENT_ID=Komodo
- KOMODO_OIDC_CLIENT_SECRET=***
- KOMODO_OIDC_USE_FULL_EMAIL=true
- KOMODO_LOGGING_LEVEL=debug
```
Komodo is sending me this error: `DEBUG AuthHandler{request=GetUser(GetUser)}: core::api::auth: /auth request e089a6cc-9f79-4d14-accc-372aea56f1dd | error: must attach either AUTHORIZATION header with jwt OR pass X-API-KEY and X-API-SECRET`

**Comment by kapsh** [comment]
@BlueCobbleStone please check Authelia logs, preferably on debug, and if it is possible also attach oidc client configuration from it.

Works here with following configuration.
Komodo core config:
```toml
oidc_enabled = true
oidc_provider = "https://auth.example.com"
oidc_redirect_host = ""
oidc_client_id = "komodo"
oidc_client_secret = "xxx"
oidc_use_full_email = false
oidc_additional_audiences = []
```
Authelia config:
```yaml
- client_id: komodo
  client_name: Komodo
  client_secret: 'xxx'
  authorization_policy: docker_users
  redirect_uris:
    - 'https://komodo.example.com/auth/oidc/callback'
  scopes:
    - openid
    - email
    - profile
  token_endpoint_auth_method: client_secret_basic
  pre_configured_consent_duration: 6 months
```
