### ISSUE TITLE
ERROR: A compose file doesn't exist after writing stack. Ensure the run_directory and file_paths are correct.

### ISSUE THREAD

**Issue by magick93** [moghtech/komodo#441]
Hi

I'm trying to import an existing docker compose file. 

I have the following settings:

![Image](https://github.com/user-attachments/assets/f8e53d6e-a392-43d9-a34a-48a349970721)

## toml

```toml
[[stack]]
name = "test"
[stack.config]
server = "darktower01"
files_on_host = true
run_directory = "/mnt/drive0/appdata/difyai/docker"
file_paths = ["docker-compose.yaml"]
```

When I `cat /mnt/drive0/appdata/difyai/docker/docker-compose.yaml` I can see the output for the docker compose file. 

But in komodo I'm getting this error:
```
ERROR: A compose file doesn't exist after writing stack. Ensure the run_directory and file_paths are correct.
```

**Comment by magick93** [comment]
I tried to `Deploy` again, and this time komodo created docker compose file:
```
## 🦎 Hello Komodo 🦎
services:
  hello_world:
    image: hello-world
    # networks:
    #   - default
    # ports:
    #   - 3000:3000
    # volumes:
    #   - data:/data

# networks:
#   default: {}

# volumes:
#   data:

```

Whereas it should have used the docker compose file I specified in the UI.
