### ISSUE TITLE
Unhealthy stack not being correctly reported

### ISSUE THREAD

**Issue by Dinth** [moghtech/komodo#464]
Hi. Today i have migrated my Nextcloud container from Portainer stack to Komodo stack (by removing it completely from Portainer first).
At the same time i have improved the compose file by adding healthcheck among other things. The healthcheck i have added is probably incorrect, nevertheless i can see that Komodo is reporting the stack as "Running", while in Portainer it shows that the stack is "Unhealthy".
I have some other containers, which are indeed marked as "Unhealthy" in Komodo, so this should work, and i doublechecked in Komodo, that the healthcheck change was correctly deployed and is indeed showing up in "Deployed config" in Info tab.
Here is the healtcheck:
```
    healthcheck:
      test:
        - CMD-SHELL
        - 'runuser -s /usr/local/bin/php - www-data /var/www/html/occ status 2>/dev/null | grep -e "installed: true" -e "maintenance: false" -e "needsDbUpgrade: false" | wc -l | [ "`cat`" = "3" ]'
      timeout: 10s
      interval: 1m0s
      retries: 5
      start_period: 10s

```
And docker inspector:
```
Health:{
FailingStreak:22,
Log:[
{
End:"2025-04-30T10:08:47.326369441+01:00",
ExitCode:1,
Output:"",
Start:"2025-04-30T10:08:47.202820485+01:00"
},
{
End:"2025-04-30T10:09:47.463403615+01:00",
ExitCode:1,
Output:"",
Start:"2025-04-30T10:09:47.327898825+01:00"
},
{
End:"2025-04-30T10:10:47.581224206+01:00",
ExitCode:1,
Output:"",
Start:"2025-04-30T10:10:47.465028861+01:00"
},
{
End:"2025-04-30T10:11:47.700561804+01:00",
ExitCode:1,
Output:"",
Start:"2025-04-30T10:11:47.582512292+01:00"
},
{
End:"2025-04-30T10:12:47.821405386+01:00",
ExitCode:1,
Output:"",
Start:"2025-04-30T10:12:47.701960932+01:00"
}
],
Status:"unhealthy"
},
```
clearly saying that the status is unhealthy. But why Komodo is not picking this up?
