### ISSUE TITLE
Inconsistent PWD for On Pull between clone and pull

### ISSUE THREAD

**Issue by bnctth** [moghtech/komodo#471]
Absolutely love Komodo, but today I ran into a bug.

I have the following repo set up:
```toml
[[repo]]
name = "homelab"
[repo.config]
server = "mia"
builder = "local"
git_account = "bnctth"
repo = "bnctth/homelab"
on_clone.command = """
  # Add multiple commands on new lines. Supports comments.
  scripts/komodo-clone.sh [[TRANSCRYPT_SECRET]]
"""
on_pull.command = """
  # Add multiple commands on new lines. Supports comments.
  scripts/komodo-pull.sh || ( cd homelab; scripts/komodo-pull.sh)
"""
```
I did not set the path for On Pull. When cloning or re-cloning the repo, both On Clone and On Pull runs in the root of my repository (say `/repos/homelab`). But when simply pulling komodo only `cd`s into `/repos`, which is the parent of my repo's root.
I'm running 1.17.4.
