### ISSUE TITLE
[BUG] wrong paths for relative volumes

### ISSUE THREAD

**Issue by jlssmt** [moghtech/komodo#475]
Hello,

I want to manage my local compose.yaml files inside komodo.
When I mount a folder inside the periphery system like this:
`- /opt:/mnt/opt`
I can see my existing stacks and access them via /mnt/opt/...

However, when I create a new stack (or redeploy an existing one) using Komodo on this periphery system, the following Compose configuration causes volume folders to be created under `/mnt/opt/gitea` instead of `/opt/gitea`.
The compose.yaml and the .env (both created by komodo) are located under the correct path instead.

Idk if komodo is deploying with absolute file paths or something like that.
Because the relative path should be always relative to the `compose.yaml` file. That's how docker is handling that.

```yaml
services:
  gitea:
    image: docker.gitea.com/gitea:latest
    env_file: .env
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres

  postgres:
    image: docker.io/library/postgres:17.4-alpine
    environment:
      - POSTGRES_USER=${GITEA__database__USER}
      - POSTGRES_PASSWORD=${GITEA__database__PASSWD}
      - POSTGRES_DB=${GITEA__database__NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
```
