### ISSUE TITLE
Pull failed on github repo: sh: 1: cd: can't cd to /home/debian/komodo

### ISSUE THREAD

**Issue by javierspn** [moghtech/komodo#506]
Hi Team!

The repo clones properly the stacks but fails when pulling.

Docker compose file of komodo:

```yaml
services:
  ferretdb:
    container_name: ${FERRET_CONTAINER_NAME}
    image: ${FERRET_CONTAINER_IMAGE}
    labels:
      komodo.skip: ""
    environment:
      TZ: ${TZ}
      FERRETDB_HANDLER: ${FERRETDB_HANDLER}
    networks:
      - proxied
    restart: ${POLICY_RESTART}
    volumes:
      - ${FERRETDB_SQLITE_VOLUME}
    logging:
      driver: ${LOG_TYPE}
      options:
        max-size: ${LOG_SIZE}
        max-file: ${LOG_FILES}
  core:
    container_name: ${KOMODO_CONTAINER_NAME}
    image: ${KOMODO_CONTAINER_IMAGE}
    labels:
      komodo.skip: ""
    environment:
      TZ: ${TZ}
      FERRETDB_HANDLER: ${FERRETDB_HANDLER}
      KOMODO_DATABASE_ADDRESS: ${FERRET_CONTAINER_NAME}
      KOMODO_DB_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DB_PASSWORD: ${KOMODO_DB_PASSWORD}
      KOMODO_PASSKEY: ${KOMODO_PASSKEY}
      KOMODO_HOST: ${KOMODO_HOST}
      KOMODO_TITLE: ${KOMODO_TITLE}
      KOMODO_FIRST_SERVER: ${KOMODO_FIRST_SERVER}
      KOMODO_DISABLE_CONFIRM_DIALOG: ${KOMODO_DISABLE_CONFIRM_DIALOG}
      KOMODO_MONITORING_INTERVAL: ${KOMODO_MONITORING_INTERVAL}
      KOMODO_RESOURCE_POLL_INTERVAL: ${KOMODO_RESOURCE_POLL_INTERVAL}
      KOMODO_WEBHOOK_SECRET: ${KOMODO_WEBHOOK_SECRET}
      KOMODO_JWT_SECRET: ${KOMODO_JWT_SECRET}
      KOMODO_LOCAL_AUTH: ${KOMODO_LOCAL_AUTH}
      KOMODO_DISABLE_USER_REGISTRATION: ${KOMODO_DISABLE_USER_REGISTRATION}
      KOMODO_ENABLE_NEW_USERS: ${KOMODO_ENABLE_NEW_USERS}
      KOMODO_DISABLE_NON_ADMIN_CREATE: ${KOMODO_DISABLE_NON_ADMIN_CREATE}
      KOMODO_TRANSPARENT_MODE: ${KOMODO_TRANSPARENT_MODE}
      KOMODO_JWT_TTL: ${KOMODO_JWT_TTL}
      KOMODO_OIDC_ENABLED: ${KOMODO_OIDC_ENABLED}
      KOMODO_OIDC_PROVIDER: ${KOMODO_OIDC_PROVIDER}
      KOMODO_OIDC_CLIENT_ID: ${KOMODO_OIDC_CLIENT_ID}
      KOMODO_OIDC_CLIENT_SECRET: ${KOMODO_OIDC_CLIENT_SECRET}
      KOMODO_OIDC_USE_FULL_EMAIL: ${KOMODO_OIDC_USE_FULL_EMAIL}
      KOMODO_GITHUB_OAUTH_ENABLED: ${KOMODO_GITHUB_OAUTH_ENABLED}
      KOMODO_GOOGLE_OAUTH_ENABLED: ${KOMODO_GOOGLE_OAUTH_ENABLED}
    networks:
      - proxied
    restart: ${POLICY_RESTART}
    depends_on:
      - ${FERRET_CONTAINER_NAME}
    volumes:
      - ${KOMODO_REPOCACHE_VOLUME}
      - ${KOMODO_REPO}
    logging:
      driver: ${LOG_TYPE}
      options:
        max-size: ${LOG_SIZE}
        max-file: ${LOG_FILES}
  periphery:
    container_name: ${PERIPHERY_CONTAINER_NAME}
    image: ${PERIPHERY_CONTAINER_IMAGE}
    labels:
      komodo.skip: ""
    environment:
      TZ: ${TZ}
      PERIPHERY_PASSKEYS: ${KOMODO_PASSKEY}
      PERIPHERY_ROOT_DIRECTORY: ${PERIPHERY_ROOT_DIRECTORY}
      PERIPHERY_SSL_ENABLED: ${PERIPHERY_SSL_ENABLED}
      PERIPHERY_INCLUDE_DISK_MOUNTS: ${PERIPHERY_INCLUDE_DISK_MOUNTS}
    networks:
      - proxied
    restart: ${POLICY_RESTART}
    volumes:
      - ${PERIPHERY_DOCKER_SOCKET_VOLUME}
      - ${PERIPHERY_PROC_VOLUME}
      - ${PERIPHERY_ROOT_DIRECTORY}:${PERIPHERY_ROOT_DIRECTORY}
    logging:
      driver: ${LOG_TYPE}
      options:
        max-size: ${LOG_SIZE}
        max-file: ${LOG_FILES}
networks:
  proxied:
    name: proxied
```

Variables:

```shell
FERRET_CONTAINER_NAME=ferretdb
FERRET_CONTAINER_IMAGE=ghcr.io/ferretdb/ferretdb:1
KOMODO_CONTAINER_NAME=komodocore
KOMODO_CONTAINER_IMAGE=ghcr.io/moghtech/komodo-core:latest
PERIPHERY_CONTAINER_NAME=periphery
PERIPHERY_CONTAINER_IMAGE=ghcr.io/moghtech/komodo-periphery:latest
#COMMON VARIABLES
TZ=Europe/Madrid
POLICY_RESTART=unless-stopped
LOG_TYPE=json-file
LOG_SIZE=10M
LOG_FILES=3
#FERRETDB VARIABLES
FERRETDB_HANDLER=sqlite
#KOMODO VARIABLES
KOMODO_DB_USERNAME=XXXXXXX
KOMODO_DB_PASSWORD=XXXXXXX
KOMODO_PASSKEY='XXXXXXXXXXXXXXXXX'
KOMODO_HOST=https://xxx.example.com
KOMODO_TITLE=Komodo
KOMODO_FIRST_SERVER=https://periphery:8120
KOMODO_DISABLE_CONFIRM_DIALOG=false
KOMODO_MONITORING_INTERVAL="15-sec"
KOMODO_RESOURCE_POLL_INTERVAL="5-min"
KOMODO_WEBHOOK_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
KOMODO_JWT_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
KOMODO_LOCAL_AUTH=true
KOMODO_DISABLE_USER_REGISTRATION=false
KOMODO_ENABLE_NEW_USERS=false
KOMODO_DISABLE_NON_ADMIN_CREATE=false
KOMODO_TRANSPARENT_MODE=false
KOMODO_JWT_TTL="1-day"
KOMODO_OIDC_ENABLED=true
KOMODO_OIDC_PROVIDER="https://XXXXXXXX"
KOMODO_OIDC_CLIENT_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
KOMODO_OIDC_CLIENT_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
KOMODO_OIDC_USE_FULL_EMAIL=true
KOMODO_GITHUB_OAUTH_ENABLED=false
KOMODO_GOOGLE_OAUTH_ENABLED=false
#PERIPHERY VARIABLES
PERIPHERY_ROOT_DIRECTORY=/etc/komodo
PERIPHERY_SSL_ENABLED=true
PERIPHERY_INCLUDE_DISK_MOUNTS=/etc/hostname
#FERRETDB VOLUMES
FERRETDB_SQLITE_VOLUME=/docker/data/komodo/ferretdb/sqlite/data:/state
#KOMODO VOLUMES
KOMODO_REPOCACHE_VOLUME=/docker/data/komodo/repocache:/repo-cache
KOMODO_REPO=/home/debian/komodo:/home/debian/komodo
#PERIPHERY VOLUMES
PERIPHERY_DOCKER_SOCKET_VOLUME=/var/run/docker.sock:/var/run/docker.sock
PERIPHERY_PROC_VOLUME=/proc:/proc
```

And this is the configuration of the repo:

```toml
[[repo]]
name = "komodostacks"
[repo.config]
server = "server-sclfp"
builder = "local"
git_account = "xxxx"
repo = "xxxxx/komodostacks"
path = "/home/debian/komodo"
webhook_secret = "xxxxxx"
```

And this is the error:

![Image](https://github.com/user-attachments/assets/f82a2226-0baa-4893-97a2-d5b97fab9856)

The container is running as root (GUID and GID are 0 (zero) both) and the root user has the proper permissions there.

Any suggestions here?

Thanks!
