### ISSUE TITLE
MongoDB - AuthenticationFailed

### ISSUE THREAD

**Issue by wardwygaerts** [moghtech/komodo#516]
I wanted to test komodo and tried with MongoDB, but failes
```
komodo-core        | Error: task 9 panicked with message "called `Result::unwrap()` on an `Err` value: failed to initialize database client\n\nCaused by:\n    failed to create index | index: enabled | error: Error { kind: Authentication { message: \"SCRAM failure: Authentication failed.\" }, labels: {}, wire_version: None, source: Some(Error { kind: Command(CommandError { code: 18, code_name: \"AuthenticationFailed\", message: \"Authentication failed.\", topology_version: None }), labels: {}, wire_version: None, source: None }) }"
```

No error in mongodb

When using postgres, everything is working fine, but I prefer not to have the additional ferret layer.

```
services:
  mongo:
    image: mongo
    labels:
      komodo.skip: null # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    # ports:
    #   - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${KOMODO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${KOMODO_DB_PASSWORD}
  core:
    image: ghcr.io/moghtech/komodo-core:latest
    container_name: komodo-core
    labels:
      komodo.skip: null
    restart: unless-stopped
    depends_on:
      #- ferretdb
      - mongo
    logging:
      driver: local
    ports:
      - 9120:9120
    env_file: .env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      ## Core cache for repos for latest commit hash / contents
      - repo-cache:/repo-cache
      ## Store sync files on server
      # - /path/to/syncs:/syncs
```

**Comment by cehenriques** [comment]
I had 2 issues with the Mongo setup that I solved:
- First, the Mongo compose didn't have the "env_file" property to pass the environment variables from the compose.env file.
- Second, I had issues running Mongo on my Proxmox VM - "MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!". Solved it by changing the CPU typo to "Host" on the VM settings.

**Comment by EliasMasche** [comment]
I am having the same issue, too

```rust
called `Result::unwrap()` on an `Err` value: failed to initialize database client

Caused by:

    failed to create index | index: enabled | error: Error { kind: Authentication { message: "SCRAM failure: Authentication failed." }, labels: {}, wire_version: None, source: Some(Error { kind: Command(CommandError { code: 18, code_name: "AuthenticationFailed", message: "Authentication failed.", topology_version: None }), labels: {}, wire_version: None, source: None }) }

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Error: task 5 panicked with message "called `Result::unwrap()` on an `Err` value: failed to initialize database client\n\nCaused by:\n    failed to create index | index: enabled | error: Error { kind: Authentication { message: \"SCRAM failure: Authentication failed.\" }, labels: {}, wire_version: None, source: Some(Error { kind: Command(CommandError { code: 18, code_name: \"AuthenticationFailed\", message: \"Authentication failed.\", topology_version: None }), labels: {}, wire_version: None, source: None }) }"
```

Running on bare metal, my CPU supports AVX, and adding `env_file: ./compose.env` didn't help either

**Comment by wardwygaerts** [comment]
> I had a similar problem. Did you solve it? [@wardwygaerts](https://github.com/wardwygaerts)

I removed everything, added a network and redeployed. Everything's working fine now

**Comment by EliasMasche** [comment]
Can you share your changes to verify if it will work on my side, too?

**Comment by wardwygaerts** [comment]
@EliasMasche :

docker-compose:
```
services:
  mongo:
    image: mongo
    container_name: komodo-mongo
    labels:
      komodo.skip: null
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    networks:
      - local
    # ports:
    #   - 27017:27017
    env_file: .env
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
  core:
    image: ghcr.io/moghtech/komodo-core:latest
    container_name: komodo-core
    labels:
      komodo.skip: null
    restart: unless-stopped
    depends_on:
      - mongo
    logging:
      driver: local
    networks:
      - local
    ports:
      - 9121:9120
    env_file: .env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
      #KOMODO_DATABASE_URI: mongodb://${KOMODO_DB_USERNAME}:${KOMODO_DB_PASSWORD}@ferretdb:27017/${KOMODO_DATABASE_DB_NAME:-komodo}?authMechanism=PLAIN
    volumes:
      - repo-cache:/repo-cache
volumes:
  # Mongo
  mongo-data: null
  mongo-config: null
  repo-cache: null
networks:
  local:
    external: true
```

env:
```
# DB credentials
KOMODO_DB_USERNAME=admin
KOMODO_DB_PASSWORD=*************************

# Configure a secure passkey to authenticate between Core / Periphery.
KOMODO_PASSKEY=*******************************

# General
KOMODO_HOST=http://192.x.x.x:9121
KOMODO_TITLE=Komodo
KOMODO_DISABLE_CONFIRM_DIALOG=false

KOMODO_MONITORING_INTERVAL="15-sec"
KOMODO_RESOURCE_POLL_INTERVAL="5-min"

# Secrets
KOMODO_WEBHOOK_SECRET=a_random_secret
KOMODO_JWT_SECRET=a_random_jwt_secret

# Auth
KOMODO_LOCAL_AUTH=true
KOMODO_DISABLE_USER_REGISTRATION=false
KOMODO_ENABLE_NEW_USERS=true
KOMODO_DISABLE_NON_ADMIN_CREATE=false
KOMODO_TRANSPARENT_MODE=false

KOMODO_JWT_TTL="1-day"
```

**Comment by EliasMasche** [comment]
Thanks with this was enough for the trick, now it works fine.
```yaml
networks:
  local:
    external: true
```
