### ISSUE TITLE
Cannot connect to Periphery on subpath

### ISSUE THREAD

**Issue by Avalancs** [moghtech/komodo#518]
I wanted to set up periphery on my servers as `https://<my server url>/komodo` with traefik doing the reverse proxying to the correct container and port. I can access periperhy on said url when I try it in the browser (I get the error text that the passkey is missing), but if I use said url in Komodo core the server will always remain unavailable.

If I change the proxying to  `https://<my server url>:10000` then it works from both the browser and Komodo core. I would like to be able to connect to Periphery even if it is on a subpath.

Example `docker-compose.yml` with the traefik flags for `/komodo` subpath reverse proxying with https, using the default .env file that comes with Komodo
```yaml
services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo-periphery
    restart: unless-stopped
    ports:
      - 127.0.0.1:8120:8120
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    env_file: ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${PERIPHERY_ROOT_DIRECTORY}:${PERIPHERY_ROOT_DIRECTORY}
    networks:
      - traefik
    labels:
      - "komodo.skip=true"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.komodo-periph-secure.rule=Host(`<my server url>`) && PathPrefix(`/komodo`)"
      - "traefik.http.routers.komodo-periph-secure.tls=true"
      - "traefik.http.services.komodo-periph-secure.loadbalancer.server.port=8120"
      - "traefik.http.routers.komodo-periph-secure.entrypoints=https"
      - "traefik.http.routers.komodo-periph-secure.tls.domains[0].main=<my server url>"
      - "traefik.http.routers.komodo-periph-secure.tls.domains[0].sans=*.<my server url>"

networks:
  traefik:
     external: true
```
