### ISSUE TITLE
[Request] Implement Healthchecks

### ISSUE THREAD

**Issue by Norrodar** [moghtech/komodo#531]
I like to monitor all my containers for their health status — mostly just to satisfy my inner monk.
![Image](https://media.tenor.com/gJ0aexM3UN4AAAAM/monk-adrian-monk.gif)

✅ **Postgres** is straightforward:
```
healthcheck:
  test:
    - CMD-SHELL
    - pg_isready -U ${KOMODO_DB_USERNAME} -d ${KOMODO_DATABASE_DB_NAME}
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 30s
```

✅ **FerretDB** has its own internal healthcheck, which communicates with Docker (e.g., for Dockge).

⚠️ For **Core**, I built the absolute basics:
```
healthcheck:
  test:
    - CMD
    - curl
    - -f
    - http://localhost:9120
  interval: 30s
  timeout: 10s
  retries: 5
```
🛑 **Periphery**... yeah, I can't get it working — the passkey header and everything just don't seem to play nice.
