### ISSUE TITLE
[Bug] git can't resolve hostname/container_name

### ISSUE THREAD

**Issue by Norrodar** [moghtech/komodo#537]
Hey :)

I want to use hostnames instead of IPs or domains.
I have two composes and 3 Docker-Networks:

Both composes have these networks:
- networks
-- internal (bridging to br0; to handle stack-internal traffic server<>db)
-- reverse-proxy-net (ipvlan, the bridge to the interface)
-- dockerwide-internal (connects all stacks together)

Why I'm using dockerwide-internal?
Because I don't want traffic between different Docker Stacks to go outside and to stay inside docker.
So komodo can ping and curl forgejo by just using the hostname "forgejo".
This is working from inside the komodo-container: (see green arrows)

![Image](https://github.com/user-attachments/assets/1d29803a-b411-40d0-a465-f816b26b576a)

If I'm adding a provider to komodo using "forgejo:3000" and bringing this to a stack, the info-tab is showing the right compose.yaml.
But when I'm trying to pull from that repo I always get this:

![Image](https://github.com/user-attachments/assets/babc352f-6858-4c1a-bab9-45eb2f79b304)

If I'm using the IP address everything is fine.
I also know that it's possible to bring in "extra_hosts", but this doesn't makes it easier. Using hostnames/container_names is just simple and easy.

I'll show you my both composes. You also can see my network-constellation in the first screenshot.

**forgejo-compose:**
```
services:
  #
  # 1. Forgejo
  #
  forgejo:
    image: codeberg.org/forgejo/forgejo:11
    container_name: forgejo
    restart: unless-stopped
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=forgejo-db:5432
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASSWORD}
    volumes:
      - ${APPDATA_PATH}/data:/data
      - ${APPCACHE_PATH}/lfs:/data/lfs
    networks:
      reverse-proxy-net:
        ipv4_address: ${IPV4}
      internal: null
      dockerwide-internal: null
    depends_on:
      - forgejo-db
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:3000/api/healthz
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - com.renovate.include=true
      - com.centurylinklabs.watchtower.enable=false
  #
  # 2. Forgejo DB
  #
  forgejo-db:
    image: postgres:14
    container_name: forgejo-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${USERDATA_PATH}/postgresql:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - com.renovate.include=true
      - com.centurylinklabs.watchtower.enable=false
#
# 3. Networks
#
networks:
  internal:
    driver: bridge
  dockerwide-internal:
    external: true
  reverse-proxy-net:
    external: true
    name: ${INTERFACE:-br0}

```

**Komodo-compose:**
```
services:
  #
  # 1. Datenbank postgres
  #
  postgres:
    image: postgres:17
    container_name: komodo_postgres
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    # ports:
    #   - 5432:5432
    volumes:
      #  - pg-data:/var/lib/postgresql/data
      - ${APPDATA_PATH}/pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${KOMODO_DB_USERNAME}
      - POSTGRES_PASSWORD=${KOMODO_DB_PASSWORD}
      - POSTGRES_DB=${KOMODO_DATABASE_DB_NAME:-komodo}
    networks:
      - internal
    labels:
      komodo.skip: true
      com.renovate.include: true
      com.centurylinklabs.watchtower.enable: false
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${KOMODO_DB_USERNAME} -d ${KOMODO_DATABASE_DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  #
  # 1. Datenbank Ferret
  #
  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:1
    container_name: komodo_ferretdb
    restart: unless-stopped
    depends_on:
      - postgres
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    # ports:
    #   - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:5432/${KOMODO_DATABASE_DB_NAME:-komodo}
    networks:
      - internal
    labels:
      komodo.skip: true
      com.renovate.include: true
      com.centurylinklabs.watchtower.enable: false
  #
  # 2. Core Service
  #
  core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo_core
    restart: unless-stopped
    depends_on:
      - ferretdb
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    #ports:
    #  - 9120:9120
    env_file: ./.env
    environment:
      KOMODO_DATABASE_URI: mongodb://${KOMODO_DB_USERNAME}:${KOMODO_DB_PASSWORD}@ferretdb:27017/${KOMODO_DATABASE_DB_NAME:-komodo}?authMechanism=PLAIN
    volumes:
      ## Core cache for repos for latest commit hash / contents
      #- repo-cache:/repo-cache
      - ${APPCACHE_PATH}/repo-cache:/repo-cache
      ## Store sync files on server
      # - /path/to/syncs:/syncs
      ## Optionally mount a custom core.config.toml
      # - /path/to/core.config.toml:/config/config.toml
      ## Allows for systemd Periphery connection at 
      ## "http://host.docker.internal:8120"
      # extra_hosts:
      #   - host.docker.internal:host-gateway
    networks:
      reverse-proxy-net:
        ipv4_address: ${KOMODO_IPV4}
      internal: null
      dockerwide-internal: null
    labels:
      komodo.skip: true
      com.renovate.include: true
      com.centurylinklabs.watchtower.enable: false
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9120
      interval: 30s
      timeout: 10s
      retries: 5
  #
  # 3. Periphery Service
  #
  ## Deploy Periphery container using this block,
  ## or deploy the Periphery binary with systemd using 
  ## https://github.com/moghtech/komodo/tree/main/scripts
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo_periphery
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    env_file: ./.env
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    networks:
      - internal
    labels:
      komodo.skip: true
      com.renovate.include: true
      com.centurylinklabs.watchtower.enable: false
#
# Networks
#
networks:
  internal:
    driver: bridge
  dockerwide-internal:
    external: true
  reverse-proxy-net:
    external: true
    name: ${INTERFACE}
```
