### ISSUE TITLE
NFS mounts are ignored in Disks stats

### ISSUE THREAD

**Issue by kiler129** [moghtech/komodo#570]
Periphery seems to ignore NFS mounts when displaying disk stats:

![Image](https://github.com/user-attachments/assets/76258ad8-1a8d-4093-afdf-6eed0e30b9b6)

I found that [`get_disks()` in stats.rs](https://github.com/moghtech/komodo/blob/4cc0817b0f6d661961a628c71e5936fd5ad43d70/bin/periphery/src/stats.rs#L108-L147) is responsible for listing disks in periphery's source code. However, the mount is neither `overlayfs` nor I defined either `PERIPHERY_INCLUDE_DISK_MOUNTS` or `PERIPHERY_EXCLUDE_DISK_MOUNTS`. 

From the container side this is how the userland sees it:
```
# docker exec komodo-periphery-1 mount | grep '.disk-size'
<nfsServer>:/exports/.disk-size on /mnt/app-data/.disk-size type nfs4 (ro,....)
/dev/sdc1 on /mnt/docker-data/.disk-size type ext4 (ro,noatime,discard)
```

The NFS mount is created on the host (via standard `/etc/fstab`) and bound to the container like so:
```yaml
    periphery:
        image: ghcr.io/moghtech/komodo-periphery:1.18.0
        # ....
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/proc
            - /mnt/app-data/.disk-size:/mnt/app-data/.disk-size:ro
            - /mnt/docker-data/.disk-size:/mnt/docker-data/.disk-size:ro
```

Are there any other debugging steps I can perform?
