### ISSUE TITLE
Unable to pull private packages via registry credentials

### ISSUE THREAD

**Issue by undaunt** [moghtech/komodo#575]
Hello,

I've been reading and re-reading https://komo.do/docs/build-images/configuration and https://komo.do/docs/connect-servers trying to see if I am missing something. I have tried creating credentials for my Github token via both config.toml files for config and periphery, through the UI, and both together. I cannot seem to pull packages on private repos directly.

![Image](https://github.com/user-attachments/assets/fdee7303-2623-42a1-924d-6dfb780e4e28)

Is this a known limitation? I've tried to move the building to local and just clone the private repo instead but that is only working on one of the two repos in question.

![Image](https://github.com/user-attachments/assets/156531f7-da45-41b5-b831-cb75d345b78d)

I've also tested against the docker socket directly instead of using a socket proxy, just in case. I still get 401s. What is the intended way to do this, if any?

```
services:
  komodo:
    image: ghcr.io/moghtech/komodo-core:latest
    container_name: komodo
    restart: unless-stopped
    depends_on:
      - komodo-db
    networks:
      - ${PROXY_NETWORK}
      - ${APP_NETWORK}
    volumes:
      - ${APPDATA_DIR}/komodo/repo-cache:/repo-cache
      - ${APPDATA_DIR}/komodo/action-cache:/action-cache
      - ${APPDATA_DIR}/komodo/syncs:/syncs
      #- ${APPDATA_DIR}/komodo/config/core.config.toml:/config/config.toml
    environment:
      TZ: ${TZ}
      KOMODO_DATABASE_ADDRESS: komodo-db:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
      KOMODO_HOST: https://${SUB_KOMODO}.${DOMAINNAME}
      KOMODO_TITLE: Komodo
      KOMODO_FIRST_SERVER: http://komodo-periphery:8120
      KOMODO_DISABLE_CONFIRM_DIALOG: false
      KOMODO_PASSKEY: ${KOMODO_PASSKEY}
      KOMODO_WEBHOOK_SECRET: ${KOMODO_WEBHOOK_SECRET}
      KOMODO_JWT_SECRET: ${KOMODO_JWT_SECRET}
      KOMODO_LOCAL_AUTH: false
      KOMODO_DISABLE_USER_REGISTRATION: true
      KOMODO_ENABLE_NEW_USERS: false
      KOMODO_DISABLE_NON_ADMIN_CREATE: true
      KOMODO_TRANSPARENT_MODE: false
      KOMODO_OIDC_ENABLED: true
      KOMODO_OIDC_PROVIDER: https://${SUB_POCKET_ID}.${DOMAINNAME}
      KOMODO_OIDC_CLIENT_ID: ${KOMODO_OIDC_CLIENT_ID}
      KOMODO_OIDC_CLIENT_SECRET: ${KOMODO_OIDC_CLIENT_SECRET}
      KOMODO_OIDC_USE_FULL_EMAIL: true
    labels:
      komodo.skip:

  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:latest
    container_name: komodo-periphery
    networks:
      - ${APP_NETWORK}
      - ${SOCKET_NETWORK}
    #command: periphery --config-path /config/periphery.config.toml
    environment:
      PERIPHERY_ROOT_DIRECTORY: ${APPDATA_DIR}/komodo
      DOCKER_HOST: tcp://socket-proxy:2375
      PERIPHERY_PASSKEYS: ${KOMODO_PASSKEY}
      PERIPHERY_SSL_ENABLED: false
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
    volumes:
      - /proc:/proc
      - ${DOCKER_DIR}:${DOCKER_DIR}
      #- ${APPDATA_DIR}/komodo/config/periphery.config.toml:/config/periphery.config.toml
      - ${APPDATA_DIR}/komodo/builds:${APPDATA_DIR}/komodo/builds
      - ${APPDATA_DIR}/komodo/repos:${APPDATA_DIR}/komodo/repos
      - ${APPDATA_DIR}/komodo/stacks:${APPDATA_DIR}/komodo/stacks
    labels:
      komodo.skip:

  komodo-db:
    image: mongo:latest
    container_name: komodo-db
    restart: unless-stopped
    networks:
      - ${APP_NETWORK}
    command: --quiet --wiredTigerCacheSizeGB 0.25
    volumes:
      - ${APPDATA_DIR}/komodo/mongo/configdb:/data/configdb
      - ${APPDATA_DIR}/komodo/mongo/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
    labels:
      komodo.skip:"postgres://${KOMODO_DB_USERNAME}:${KOMODO_DB_PASSWORD}@komodo-db:27017" }'

```

Thank you!
