### ISSUE TITLE
[bug] OIDC - wrong authorization url

### ISSUE THREAD

**Issue by enimog** [moghtech/komodo#599]
Hello,
I had some issue configuring OIDC. I wanted to use it with authentik. I followed all instructions. My compose.env contains this:
```
KOMODO_OIDC_ENABLED=true
KOMODO_OIDC_PROVIDER=https://auth.<domain>/application/o/komodo/
KOMODO_OIDC_REDIRECT_HOST=https://komodo.<domain>
KOMODO_OIDC_CLIENT_ID=<client id>
KOMODO_OIDC_CLIENT_SECRET=<secret>
KOMODO_OIDC_USE_FULL_EMAIL=true
```

And when clicking on the OIDC login button, it redirected me to the komodo login page without doing anything. After investigating, I found out that it was sending the authorization url at https://_**komodo**_.domain/application/o/authorize/?response_type=code&client_id=...&redirect_uri=https://komodo.domain/auth/oidc/callback instead of auth as it should have.

So I did some patch on my side in my traefik config
```
  middlewares:
    komodo-oidc-redirect:
      redirectRegex:
        regex: ^https://komodo\.<domain>/application/o/(.*)
        replacement: https://auth.<domain>/application/o/$1
        permanent: false
```

and now everything work. Not sure why I had this issue, thought it was a good idea to report it.
