### ISSUE TITLE
Entrypoint.sh is being ignored in Komodo Stacks

### ISSUE THREAD

**Issue by naby-dev** [moghtech/komodo#619]
Hi 
I am making use of stacks that is available on my server but the docker compose file is not using the entrypoint.sh
The entrypoint,sh is executable and available in the same folder as the stack. 
This does work in my host terminal but not via komodo stacks
```
networks:
  mediarr-network:
    external: true

services:
  rclone:
    container_name: rclone
    image: rclone/rclone:latest
    restart: unless-stopped
    ports:
     - 5572:5572
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${REMOTE_MOUNT}:/data:rshared
      - ${DOCKER_APPDATA}/rclone/rclone.conf:/config/rclone/rclone.conf
      - ${DOCKER_APPDATA}/rclone/cache:/cache
      - ./entrypoint.sh:/entrypoint.sh
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    stop_grace_period: 30s
    init: true
    networks:
      - mediarr-network

```

entrypoint.sh
```
#!/bin/sh

# function to handle cleanup on shut-down
cleanup() {
    echo "Received shutdown signal, cleaning up..."
    umount -l /data
    exit 0
}

# trap SIGTERM and SIGINT signals and call cleanup()
trap cleanup TERM INT

# Mount the union remote
rclone mount decypharr: /data \
  --allow-other \
  --allow-non-empty \
  --uid=1000 \
  --gid=1000 \
  --umask=002 \
  --vfs-cache-mode=full \
  --vfs-cache-max-size=40G \
  --vfs-cache-max-age=18h \
  --vfs-cache-poll-interval=2m \
  --vfs-read-chunk-size=128M \
  --vfs-read-chunk-size-limit=1024M \
  --vfs-read-ahead=512M \
  --buffer-size=256M \
  --cache-dir=/cache \
  --vfs-fast-fingerprint \
  --attr-timeout=2h \
  --async-read=true \
  --vfs-refresh \
  --no-checksum \
  --no-modtime \
  --use-mmap \
  --rc \
  --rc-addr=:5572 \
  --rc-no-auth \
  --rc-web-gui \
  --log-level=INFO &

RCLONE_PID1=$!

# Wait for both mounts to exit
wait $RCLONE_PID1


# final cleanup in case of unexpected exit
cleanup
```
