### ISSUE TITLE
Newline characters in a variable causes perpetual ResourceSyncPendingUpdate state

### ISSUE THREAD

**Issue by oblivioncth** [moghtech/komodo#627]
```toml
[[variable]]
name = "ADHOC_STACKS"
value = """
gitea
pgadmin"""
is_secret = false
```

Seems that komodo stores the value correctly in TOML using a literal string, but this somehow confuses Komodo's sync status checker after committing this change the Pending status is never cleared and Komodo shows the same content on both sides of the diff comparison with no change markers.

Storing multi-line variables is convenient for use in Actions where an array is expected.
