### ISSUE TITLE
Komodo variable name used instead of stack name

### ISSUE THREAD

**Issue by SBado** [moghtech/komodo#628]
There seems to be a problem when the value of a variable is equal to or is included into the name of a service in a stack. For example, given the following compose.yaml:

```
services:
  esphome:
    image: "ghcr.io/esphome/esphome"
    container_name: "esphome"
    environment:
      - "USERNAME=${ESPHOME_USER}"
      - "PASSWORD=${ESPHOME_PASSWORD}"
      - "ESPHOME_DASHBOARD_USE_PING=false"
    network_mode: "host"
    restart: "unless-stopped"
```

If the value of the variable **ESPHOME_USER** is **esp**, the following command is shown in the "Compose Up" stage:

`cd /mnt/tank/appsdata/komodo/periphery/stacks/<ESPHOME_USER>home/stacks/coreos/<ESPHOME_USER>home && docker compose -p <ESPHOME_USER>home -f compose.yaml --env-file .env up -d`

While it should be:

`cd /mnt/tank/appsdata/komodo/periphery/stacks/esphome/stacks/coreos/esphome && docker compose -p esphome -f compose.yaml --env-file .env up -d`

The deployment seems successful (I can see the container running using `docker ps`), but the stack is marked as **down** (in the stack page,  the **Services** and **Log** tabs are disabled). Why does this happen? Am I doing something wrong?
